### PR TITLE
Fix scheduler not respecting priority

### LINKED ISSUE #48: [0.7.1] default priority systems can be scheduled after systems with higher priority
## Description
When setting a system's priority higher than 0, the expectation is that it will be scheduled only after the default priority systems. In 0.7.0, this appeared to be the case, but in 0.7.1 we can observe that an `after` can "pull down" a system to a lower priority in the queue.

## Steps to reproduce

1. Download the attached zip file for a small matter project made to reproduce this behavior. [matter-repro-systems.zip](https://github.com/matter-ecs/matter/files/14513503/matter-repro-systems.zip)
2. Build/serve it to a default studio baseplate.
3. Press Play Solo.
4. Observe the output.

## Expected behavior

There are three systems in this project, `a`, `b`, and `last`. The output will print the following message describing my expectations:
```
expectation:
	system b            (default priority)
	system last         (1000 priority)
	system a            (after last)
```
## Actual behavior
On 0.7.1, we get this schedule instead:
```
system last
system a
system b
```

This is problematic because `system b` has a default priority and is being scheduled after `system last` which has a priority of 1000. My guess is that `system a`'s `after` field is "pulling down" `system last` in the schedule...

Using 0.7.0 will run the schedule as expected.

### PR DESCRIPTION
**Pull request by metrowaii**
## Proposed changes

With this new scheduler systems are assigned a priority internally. A system with no defined priority and no dependencies defaults to zero, and a system with dependencies should have a priority equal to the max priority of its dependencies + 1. We then sort the systems based on their internal priority. 

## Related issues

Closes #48

### CODE REVIEW

File: lib/Loop.lua [hunk 1]
```diff
@@ -222,9 +214,44 @@ function Loop:replaceSystem(old: System, new: System)
...
+				if system.after then
+					for _, dependency in system.after do
+						if systemPriorityMap[dependency] ~= visiting then
+							priority = math.max(priority, systemPriority(dependency) + 1)
+						else
+							error(
+								`Unable to get system priority due to cyclic dependency between: \n{systemName(system)} \nAND \n{systemName(
+									dependency
+								)}`
+							)
```
Comment (benbrimeyer) [inline lib/Loop.lua:238]: I can anticipate this error message being more clear if we indicate this is due to the after field being defined:

```suggestion
							local errorStatement = {
								"Cyclic dependency detected: System '{systemName(system)}' is set to execute after System 'systemName(dependency)', and vice versa. This creates a loop that prevents the systems from being able to execute in a valid order.",
								"To resolve this issue, reconsider the dependencies between these systems. One possible solution is to update the 'after' field from one of the systems.",
							}
							error(table.concat(errorStatement, "\n"))
```

**Review by benbrimeyer — APPROVED** [review]
Thanks for taking a look into this. I have one consideration on making the developer-ux a bit more clear when I (inevitable) encounter this error again, but feel free to pass on it

**Review by Ukendio — APPROVED** [review]
lgtm!
